[package]
name = "builtins-hints"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = {version="*", features=["rand"]}
num-integer= "*"
num-traits = "*"
lazy_static = "*"
rand = "*"